server:
  port: 8073

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.yang.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: microservicecloud-dept                            #对外暴露的微服务的名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB03              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间


#添加了这个配置(eureka)这个项目就变成了eureka的客户端
eureka:
  client:
    service-url:
      #单机版的配置：
      #defaultZone: http://localhost:7081/eureka
      #集群版的配置：
      defaultZone: http://localhost:7081/eureka,http://localhost:7082/eureka,http://localhost:7083/eureka
  instance:
    instance-id : microservicecloud-dept:8073
    prefer-ip-address: true
info:
  app.name: yang-microservicecloud
  company.name: www.yang.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

